---
title: "Exercicio_2"
author: "André Viola"
date: "4/9/2021"
output:
  html_document:
    df_print: paged
---


```{r, echo=FALSE}

knitr::opts_chunk$set(echo=FALSE,error=FALSE,warning=FALSE,message=FALSE)

```

```{r}
library("tidyverse")
library("tidylog")
library("nycflights13")
```

```{r}
flights
names(flights)
```
```{r}
#reneame
flights_renamed <- flights %>% rename(arrival_time = arr_time)
flights <- flights %>% rename(arrival_time=arr_time)
#renaming multiple variables
flights <- flights %>% rename (destination = dest, 
                               arrival_delay = arr_delay,
                               departure_delay=dep_delay)

```

```{r}
#select
flights %>% select(year, month, day)
```

```{r}
#mutate
#creating a new variable based on existing ones
flights <-flights %>% mutate(dep_delay_double = departure_delay*2)
#changing an existing variable
flights <- flights %>% mutate(departure_delay=departure_delay*60)
#changing a variable using functions (in this case we use tolower to change the vairable origin from upper case to lower case)

flights <- flights %>% mutate(origin = tolower(origin))

```

```{r}
#slice
#limiting our observations to just the fith line of the dataset

flights %>% slice(5)
#selecting the first five lines 

flights %>% slice(1:5)
```

```{r}
#numeric sets
#in order to select the observations we have to create a vector with the positions of the wanted elements
wanted_lines <- c(1,4,5,8,22,169)
#then we proceed by using this vector, calling it by name, inside the function slice
flights %>% slice(wanted_lines)
#we can also select the non-wanted observations inserting the "-" signal in front of the number
flights %>% slice(-1)
#for a set of numbers we use : in order to indicate a sequential set of numbers 
flights %>% slice(10:20)
#for more systematic non-sequential sets we can use the function seq() 
#it has three parameters: initial value (from),final value(to) and an increment (by)
flights %>% slice(seq(from=1,
                      to=100,
                      by=10))
#or
flights %>% slice(seq(1,100,10))
```


```{r}
#filter
#variable name +operation+criteria
flights_july <-flights %>% filter(month == 6)
#we can combine criteria using the symbol &
flights_july_5 <- flights %>% filter(month == 6 & day == 5)
#including < or > we can generate comparisons 
flights_july_5_morning <- flights %>% filter(month == 6 & day == 5 & departure_time < 1200)

#all the flights that delayed for more than 50 minutes and departed before 5 a.m. or that arrived in Atlanta(ATL)

flights %>% filter((departure_time<=500 | destination == "ATL") & arrival_delay>=50)

#asking the opposite with the ! symbol

flights %>% filter(!((departure_time<=500 | destination == "ATL") & arrival_delay>=50))

```

```{r}
#combining manipulations

flights %>% 
  rename(arrival_time=arr_time) %>%
  mutate(departure_delay=departure_delay*60) %>%
  filter(month == 6 & day == 5) %>%
  select(year,month,day,arrival_time,departure_delay)
```

```{r}
library(tidyverse)
#opening data 

#opening online links
#saving the url of the link and then opening it
file1 <- "https://raw.githubusercontent.com/leobarone/ifch_intro_r/master/data/bf_amostra_hv.csv"

dados <- read_csv(file1)

#read_delim gives us more flexibility to deal with uncommon files
#e.g. by default we use comma on read_csv but data in Brazil is separated by a ; because comma in Brazil is a decimal separator

dados <- read_delim(file1,
                    delim = ",")


file_semi_colon <- "https://raw.githubusercontent.com/leobarone/ifch_intro_r/master/data/bf_amostra_hp.csv"
dados <- read_delim(file_semi_colon,
                    delim = ";")

file_tab <- "https://raw.githubusercontent.com/leobarone/ifch_intro_r/master/data/bf_amostra_ht.csv"
dados<- read_delim(file_tab,
                   delim="\t")

#the pattern of read_delim is to import the first line as the name of the variables, if our data do not have a header the first line of data will wrongly become the name of the variables . 
#In order to fix this problem we use the argument col_names which must be equal to FALSE for the data stored without column names

file_sem_header <- "https://raw.githubusercontent.com/leobarone/ifch_intro_r/master/data/bf_amostra_nv.csv"

dados <- read_delim(file_sem_header,
                  col_names = F,
                  delim= ",")

#we can also put the name of the columns as an argument

dados <- read_delim(file_sem_header,
                    col_names=c("estado","municipio_cod","municipio_nome",
                                "NIS","transferido"),
                    delim=",")

#sometimes it is good to define the class of the imported variables in order to avoid new transformations once they are imported. The argument col_types must be a sequence of of character where c = character, d=double, L=logical, i=integer 
dados <- read_delim(file1, 
                    delim = ",", 
                    col_types = "cicid")
#using locale in order to specify some characteristics

dados <- read_delim(file1,
                    delim=",",
                    locale=locale(decimal_mark=",", grouping_mark="."))
#encoding
dados <- read_delim(file1,
                    delim=",",
                    local=locale(encoding="latin1"))

```

```{r}
#excel data
library(readxl)

excel_sheets("Base 2005.xls")


#importing the variables from "variaveis exernas"
#1
externas <- read_excel("Base 2005.xls","Variáveis externas")
#2
externas <- read_excel("Base 2005.xls",11)
```
```{r}
#SPSS and STATA data

library("haven")
#read_sas SAS
#read_stata STATA
#read_dta STATA
#read_sav SPSS
#read_por SPSS

latino_barometro_SPSS <- read_spss("Latinobarometro_2015_Eng.sav")

latino_barometro_stata <- read_stata("Latinobarometro_2015_Eng.dta")

```

